### 获取信息
GET http://localhost:3001/api/userInfoFile
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYTYyMmJiNDM4MzYyM2M0ODkzOGNiMCIsImlhdCI6MTYwNDkwNzAyN30.Utb9AcBPd1OZ5RilSH55nRzfZkbELeKCNwFlsz2QGfQ

{
}

###

### 登录
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "admin3",
  "password": "admin"
}

###


###
#注册
POST http://localhost:3001/api/register
Content-Type: application/json

{
  "username": "admin4",
  "password": "admin"
}



###
POST http://localhost:3001
Content-Type: application/json



### 所有用户
GET http://localhost:3001/api/users
Accept: application/json



